# Generated by Django 5.1.3 on 2024-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_details_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="details",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
