# Generated by Django 5.1.3 on 2024-12-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_notes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
