# Generated by Django 5.1.3 on 2024-12-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_notes", "0002_uploadnotes_delete_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("file", models.FileField(blank=True, null=True, upload_to="notes/")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="notes/images/"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UploadNotes",
        ),
    ]
